# Generated by Django 3.2.7 on 2021-09-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrgini_admin', '0002_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='password',
            field=models.TextField(blank=True),
        ),
    ]
