# Generated by Django 3.2.7 on 2021-09-21 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrgini_admin', '0003_applicant_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
